"""
Ollama LLM generation service.
Generates structured answers to user questions based strictly on retrieved document context.
"""

import time
import ollama

from app.core.exceptions import LLMGenerationError
from app.core.logging_config import get_logger
from config import (
    LLM_NUM_PREDICT,
    LLM_TEMPERATURE,
    MAX_CONTEXT_CHARS,
    OLLAMA_BASE_URL,
    OLLAMA_LLM_MODEL,
    OLLAMA_TIMEOUT,
)

logger = get_logger(__name__)

# Initialize client with configured host and timeout
_client = ollama.Client(host=OLLAMA_BASE_URL, timeout=OLLAMA_TIMEOUT)


def generate_answer(question: str, context: str) -> str:
    """
    Generate a structured answer from retrieved context using Ollama LLM.

    Args:
        question: User query string.
        context: Concatenated context chunks from retrieved documents.

    Returns:
        Generated answer string.

    Raises:
        LLMGenerationError: If the LLM call fails or times out.
    """
    truncated_context = context[:MAX_CONTEXT_CHARS]

    prompt = f"""You are a professional document QA assistant.

TASK: Answer the question based ONLY on the provided context.

FORMATTING REQUIREMENTS:
- Be clear and well-organized
- Use bullet points for multiple items
- Use numbered lists for step-by-step information
- Highlight key information
- Keep paragraphs short and readable
- If information spans multiple sections, organize by topic

RULES:
1. Use ONLY the provided context
2. Do NOT make up information
3. Be specific and relevant to the question
4. If answer is not in context, say: "This information is not available in the provided document."
5. For policies/procedures, organize in a structured way

---CONTEXT---
{truncated_context}

---QUESTION---
{question}

---ANSWER---
"""

    logger.info(f"Generating LLM response using model '{OLLAMA_LLM_MODEL}' for question: '{question[:80]}'...")
    start_time = time.time()

    try:
        response = _client.chat(
            model=OLLAMA_LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            options={
                "temperature": LLM_TEMPERATURE,
                "num_predict": LLM_NUM_PREDICT,
            },
        )

        elapsed = time.time() - start_time
        answer = response.get("message", {}).get("content", "").strip()
        logger.info(f"LLM response generated in {elapsed:.2f}s (length: {len(answer)} chars)")

        if not answer:
            logger.warning("LLM returned empty content in response.")
            return "No response generated by the model."

        return answer

    except Exception as e:
        elapsed = time.time() - start_time
        logger.error(
            f"Failed to generate LLM response after {elapsed:.2f}s using {OLLAMA_LLM_MODEL}: {e}",
            exc_info=True,
        )
        raise LLMGenerationError(f"LLM generation failed: {str(e)}") from e
